### ISSUE TITLE
Interfaz grafica

### ISSUE THREAD

**Issue by josemanuelgarcia** [Arquisoft/Trivial3b#2]
Elegir framework para la implementación de la interfaz

**Comment by josemanuelgarcia** [comment]
Sería bueno utilizar un framework para crear juegos en 2D. Por ejemplo encontre el libgdx (http://libgdx.badlogicgames.com/features.html) buscando un poco, y encima es un plugin para eclipse.
Ademas estan unity o unreal engine, pero puede que resulte algo más complicado.

**Comment by cristian3** [comment]
Voy a probar el libgdx a ver que tal va
