### ISSUE TITLE
Lógica de juego.

### ISSUE THREAD

**Issue by josemanuelgarcia** [Arquisoft/Trivial3b#3]
Decidir sobre que tipo de tablero utilizar: cuadrado o círculo

**Comment by josemanuelgarcia** [comment]
Creo qu eel metodo que calcula los caminos de longitud k, es analzar el array que devuelve dijkstra y buscar los nodos cuyo camnino minimo sea k.
Lo que falta es saber asociar cada posicion del array al nodo destino.

**Comment by dani-garcia** [comment]
Si en la salida de dijkstra buscamos las posiciones cuya distancia sea x, solo tenemos que obtener la casilla con grafo.getNodes()[posicion], y luego podemos devolver un array de casillas (o solo los ids, como veas)
